### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by D-3lf** [slackhq/goSDL#13]
### Description

Does this application use any type of authentication? If not, how is it being protected at Slack?

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [ ] bug
- [ ] enhancement (feature request)
- [ x] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/{project_slug}/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report

I do not believe this is a bug. I think there's an implementation at Slack that's not detailed in the project docs.

#### Reproducible in:

All versions/All OSs

#### Steps to reproduce:

1. Deploy app
2. Access main page

#### Expected result:

Prior to being able to interact with the application I would need to supply some type of data to verify I'm an authorized user.

#### Actual result:

App loaded and I was able to use it unchallenged.

**Comment by janmasarik** [comment]
You can use some simple proxy like https://github.com/bitly/oauth2_proxy
