### ISSUE TITLE
Slack for Debian suffers from segfault

### ISSUE THREAD

**Issue by REPTILEHAUS** [slackhq/goSDL#21]
Updated my Kali Linux box (Debian based distro x64 arch) and slack doesnt open up.. dmesg shows seg fault output here 

```
[ 1969.540044] slack[6316]: segfault at dbf060 ip 0000000000dbf060 sp 00007ffe56e72458 error 15 in slack[200000+160c000]
[ 1969.540047] Code: 50 01 60 69 36 00 b8 da 50 01 78 69 36 00 38 de 50 01 a8 69 36 00 c8 e1 50 01 d0 69 36 00 b8 e2 50 01 18 6a 36 00 f8 e2 50 01 <38> 6a 36 00 88 e3 50 01 60 6a 36 00 e8 e9 50 01 98 6a 36 00 38 ea 
[ 2051.204631] slack[6681]: segfault at dbf060 ip 0000000000dbf060 sp 00007ffeb6408748 error 15 in slack[200000+160c000]
[ 2051.204634] Code: 50 01 60 69 36 00 b8 da 50 01 78 69 36 00 38 de 50 01 a8 69 36 00 c8 e1 50 01 d0 69 36 00 b8 e2 50 01 18 6a 36 00 f8 e2 50 01 <38> 6a 36 00 88 e3 50 01 60 6a 36 00 e8 e9 50 01 98 6a 36 00 38 ea 
[ 2522.424384] slack[7282]: segfault at dbf060 ip 0000000000dbf060 sp 00007ffd096a5778 error 15 in slack[200000+160c000]
[ 2522.424387] Code: 50 01 60 69 36 00 b8 da 50 01 78 69 36 00 38 de 50 01 a8 69 36 00 c8 e1 50 01 d0 69 36 00 b8 e2 50 01 18 6a 36 00 f8 e2 50 01 <38> 6a 36 00 88 e3 50 01 60 6a 36 00 e8 e9 50 01 98 6a 36 00 38 ea 
[ 2760.019834] slack[8681]: segfault at dbf060 ip 0000000000dbf060 sp 00007ffdfc341248 error 15 in slack[200000+160c000]
[ 2760.019837] Code: 50 01 60 69 36 00 b8 da 50 01 78 69 36 00 38 de 50 01 a8 69 36 00 c8 e1 50 01 d0 69 36 00 b8 e2 50 01 18 6a 36 00 f8 e2 50 01 <38> 6a 36 00 88 e3 50 01 60 6a 36 00 e8 e9 50 01 98 6a 36 00 38 ea 
[ 3205.761886] slack[9894]: segfault at dbf060 ip 0000000000dbf060 sp 00007ffdb51936c8 error 15 in slack[200000+160c000]
[ 3205.761889] Code: 50 01 60 69 36 00 b8 da 50 01 78 69 36 00 38 de 50 01 a8 69 36 00 c8 e1 50 01 d0 69 36 00 b8 e2 50 01 18 6a 36 00 f8 e2 50 01 <38> 6a 36 00 88 e3 50 01 60 6a 36 00 e8 e9 50 01 98 6a 36 00 38 ea 
[ 4242.329214] slack[10221]: segfault at dbf060 ip 0000000000dbf060 sp 00007fffafc1fa58 error 15 in slack[200000+160c000]
[ 4242.329217] Code: 50 01 60 69 36 00 b8 da 50 01 78 69 36 00 38 de 50 01 a8 69 36 00 c8 e1 50 01 d0 69 36 00 b8 e2 50 01 18 6a 36 00 f8 e2 50 01 <38> 6a 36 00 88 e3 50 01 60 6a 36 00 e8 e9 50 01 98 6a 36 00 38 ea 
^[[A
[ 4255.544196] slack[10239]: segfault at dbf060 ip 0000000000dbf060 sp 00007ffeb6d50408 error 15 in slack[200000+160c000]
[ 4255.544199] Code: 50 01 60 69 36 00 b8 da 50 01 78 69 36 00 38 de 50 01 a8 69 36 00 c8 e1 50 01 d0 69 36 00 b8 e2 50 01 18 6a 36 00 f8 e2 50 01 <38> 6a 36 00 88 e3 50 01 60 6a 36 00 e8 e9 50 01 98 6a 36 00 38 ea 
[ 4256.638294] slack[10241]: segfault at dbf060 ip 0000000000dbf060 sp 00007fff4a61df28 error 15 in slack[200000+160c000]
[ 4256.638297] Code: 50 01 60 69 36 00 b8 da 50 01 78 69 36 00 38 de 50 01 a8 69 36 00 c8 e1 50 01 d0 69 36 00 b8 e2 50 01 18 6a 36 00 f8 e2 50 01 <38> 6a 36 00 88 e3 50 01 60 6a 36 00 e8 e9 50 01 98 6a 36 00 38 ea 
[ 4257.154284] slack[10243]: segfault at dbf060 ip 0000000000dbf060 sp 00007fff83522ae8 error 15 in slack[200000+160c000]
[ 4257.154287] Code: 50 01 60 69 36 00 b8 da 50 01 78 69 36 00 38 de 50 01 a8 69 36 00 c8 e1 50 01 d0 69 36 00 b8 e2 50 01 18 6a 36 00 f8 e2 50 01 <38> 6a 36 00 88 e3 50 01 60 6a 36 00 e8 e9 50 01 98 6a 36 00 38 ea 
```

**Comment by REPTILEHAUS** [comment]
```~/Desktop$ uname -a
Linux woirk 4.18.0-kali3-amd64 #1 SMP Debian 4.18.20-2kali2 (2018-11-30) x86_64 GNU/Linux
```

**Comment by zaquestion** [comment]
@REPTILEHAUS This issue is painful, we rely on the slack app to get our work done and its frustrating for it to be crashing. `goSDL` however would seemingly be the complete wrong place to report the issue, this should probably be closed out unless I'm missing something.

That said I was able to work around this exact issue using the tip http://ubuntuhandbook.org/index.php/2018/11/slack-app-not-launching-ubuntu-18-10/

modified for debian thats something like 
download atom deb https://atom.io/
```
sudo dpkg -i atom-amd64.deb
sudo ag -g libnode.so / --ignore-dir /var/lib/docker
sudo mv /usr/lib/slack/libnode.so /usr/lib/slack/libnode.so.bak
sudo ln /usr/share/atom/libnode.so /usr/lib/slack/libnode.so
```
Best of luck!

**Comment by REPTILEHAUS** [comment]
> @REPTILEHAUS This issue is painful, we rely on the slack app to get our work done and its frustrating for it to be crashing. `goSDL` however would seemingly be the complete wrong place to report the issue, this should probably be closed out unless I'm missing something.
> 
> That said I was able to work around this exact issue using the tip http://ubuntuhandbook.org/index.php/2018/11/slack-app-not-launching-ubuntu-18-10/
> 
> modified for debian thats something like
> download atom deb https://atom.io/
> 
> ```
> sudo dpkg -i atom-amd64.deb
> sudo ag -g libnode.so / --ignore-dir /var/lib/docker
> sudo mv /usr/lib/slack/libnode.so /usr/lib/slack/libnode.so.bak
> sudo ln /usr/share/atom/libnode.so /usr/lib/slack/libnode.so
> ```
> Best of luck!

Thanks man, i couldnt find an official Slack issues area so ended up putting in here. 

Will try it now, however I did something similar using the vscode libnode.so file - but now my slack refreshes whenever a new notification happens.

**Comment by aoberoi** [comment]
@REPTILEHAUS you can always create a support request by either using the `/feedback` command in Slack, or emailing `feedback@slack.com`.

**Comment by jerem991** [comment]
> > @REPTILEHAUS This issue is painful, we rely on the slack app to get our work done and its frustrating for it to be crashing. `goSDL` however would seemingly be the complete wrong place to report the issue, this should probably be closed out unless I'm missing something.
> > That said I was able to work around this exact issue using the tip http://ubuntuhandbook.org/index.php/2018/11/slack-app-not-launching-ubuntu-18-10/
> > modified for debian thats something like
> > download atom deb https://atom.io/
> > ```
> > sudo dpkg -i atom-amd64.deb
> > sudo ag -g libnode.so / --ignore-dir /var/lib/docker
> > sudo mv /usr/lib/slack/libnode.so /usr/lib/slack/libnode.so.bak
> > sudo ln /usr/share/atom/libnode.so /usr/lib/slack/libnode.so
> > ```
> > Best of luck!
> 
> Thanks man, i couldnt find an official Slack issues area so ended up putting in here.
> 
> Will try it now, however I did something similar using the vscode libnode.so file - but now my slack refreshes whenever a new notification happens.

This fixed the crash.
Thanks !

EDIT : Slack is not very stable with this .so, it crashes each time i receive a message, but it displays everything.
