### ISSUE TITLE
Composer replace tabs with spaces

### ISSUE THREAD

**Issue by HeathNaylor** [slackhq/goSDL#3]
### Description
The `./composer.json` file has tabs instead of spaces for one of the dependencies

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/{project_slug}/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---
#### Attachments:

![image](https://user-images.githubusercontent.com/10814256/39647876-c69036be-4f9d-11e8-9bbe-4cadc222e03c.png)

**Comment by fyunaz** [comment]
Thanks for flagging this we fixed this on our the latest commit.
