### ISSUE TITLE
CURLOPT_SSL_VERIFYPEER disabled for JIRA integration

### ISSUE THREAD

**Issue by EricEllett** [slackhq/goSDL#9]
### Description

Hello friends! It appears that the current JIRA integration doesn't enable certificate verification.

### What type of issue is this? (place an `x` in one of the `[ ]`)
- [x] bug
- [ ] enhancement (feature request)
- [ ] question
- [ ] documentation related
- [ ] testing related
- [ ] discussion

### Requirements (place an `x` in each of the `[ ]`)
* [x] I've read and understood the [Contributing guidelines](https://github.com/{project_slug}/blob/master/.github/contributing.md) and have done my best effort to follow them.
* [x] I've read and agree to the [Code of Conduct](https://slackhq.github.io/code-of-conduct).
* [x] I've searched for any related issues and avoided creating a duplicate issue.

---

### Bug Report
It appears that the CURLOPT_SSL_VERIFYPEER parameter in the https://github.com/slackhq/goSDL/blob/master/include/lib_jira.php file is currently disabled for each curl session. 

#### Reproducible in:

goSDL version: 1

{platform_name} version: N/A

OS version(s): N/A

#### Steps to reproduce:

N/A

#### Expected result:

N/A

#### Actual result:

N/A

#### Attachments:

Logs, screenshots, screencast, sample project, funny gif, etc.

**Comment by fyunaz** [comment]
Yes, we should do this!
